services:
  fastapi:
    build: ./backend
    container_name: bmi_calculator_fastapi
    restart: always
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_USER: ${user}
      POSTGRES_PASSWORD: ${password}
      POSTGRES_DB: ${dbname}
      DB_HOST: aws-0-sa-east-1.pooler.supabase.com  # Use the service name in Docker Compose
      DB_PORT: 6543
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

volumes:
  postgres_data:
