"""Adding field intolerances

Revision ID: 0e303af1a51a
Revises: 544e068aa8bc
Create Date: 2025-05-13 09:42:52.259808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e303af1a51a'
down_revision: Union[str, None] = '544e068aa8bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diets', sa.Column('intolerances', sa.String(), nullable=True))
    op.drop_column('user_bmi', 'intolerances')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_bmi', sa.Column('intolerances', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('diets', 'intolerances')
    # ### end Alembic commands ###
