"""Creating relationship between users and trainings

Revision ID: 3c9604419fbd
Revises: cf208240cb45
Create Date: 2025-04-02 09:51:32.537615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c9604419fbd'
down_revision: Union[str, None] = 'cf208240cb45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainings', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'trainings', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trainings', type_='foreignkey')
    op.drop_column('trainings', 'user_id')
    # ### end Alembic commands ###
