"""Renaming exercises to trainings

Revision ID: 3e31e61fe5f8
Revises: c39a10bb79ae
Create Date: 2025-03-29 13:04:10.781050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e31e61fe5f8'
down_revision: Union[str, None] = 'c39a10bb79ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_exercises_id', table_name='exercises')
    op.drop_table('exercises')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('bmi_status_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bmi_status_id'], ['bmi_status.id'], name='exercises_bmi_status_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='exercises_pkey')
    )
    op.create_index('ix_exercises_id', 'exercises', ['id'], unique=False)
    # ### end Alembic commands ###
