"""Adding field intolerances into UserBMI

Revision ID: 544e068aa8bc
Revises: 686380a2b50f
Create Date: 2025-05-10 13:32:01.094890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '544e068aa8bc'
down_revision: Union[str, None] = '686380a2b50f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diets', sa.Column('intolerances', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diets', 'intolerances')
    # ### end Alembic commands ###
