"""Adding the fields weight and height in the USER_BMI table

Revision ID: 5d1480b403f3
Revises: d7d0a6db548d
Create Date: 2025-04-17 10:51:52.646744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d1480b403f3'
down_revision: Union[str, None] = 'd7d0a6db548d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_bmi', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('user_bmi', sa.Column('height', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_bmi', 'height')
    op.drop_column('user_bmi', 'weight')
    # ### end Alembic commands ###
