"""Deleting the existing relationship with Exercise and Meal

Revision ID: 692a1dcbf897
Revises: cb1beca6a273
Create Date: 2025-04-28 09:11:20.034537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '692a1dcbf897'
down_revision: Union[str, None] = 'cb1beca6a273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_exercises_id', table_name='exercises')
    op.drop_table('exercises')
    op.drop_index('ix_meals_id', table_name='meals')
    op.drop_table('meals')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('diet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('bmi_status_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bmi_status_id'], ['bmi_status.id'], name='meals_bmi_status_id_fkey'),
    sa.ForeignKeyConstraint(['diet_id'], ['diets.id'], name='meals_diet_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='meals_pkey')
    )
    op.create_index('ix_meals_id', 'meals', ['id'], unique=False)
    op.create_table('exercises',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('training_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('bmi_status_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bmi_status_id'], ['bmi_status.id'], name='exercises_bmi_status_id_fkey'),
    sa.ForeignKeyConstraint(['training_id'], ['trainings.id'], name='exercises_training_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='exercises_pkey')
    )
    op.create_index('ix_exercises_id', 'exercises', ['id'], unique=False)
    # ### end Alembic commands ###
