"""Removing field free_time from Training

Revision ID: 921993e74adc
Revises: 95846d2ed53a
Create Date: 2025-05-20 11:27:21.692080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '921993e74adc'
down_revision: Union[str, None] = '95846d2ed53a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainings', 'free_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainings', sa.Column('free_time', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
