"""Removing field is_plus

Revision ID: 95846d2ed53a
Revises: a96d1067a430
Create Date: 2025-05-17 14:11:48.584617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95846d2ed53a'
down_revision: Union[str, None] = 'a96d1067a430'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_plus')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_plus', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
