"""new changes

Revision ID: 9a7ebe803dc4
Revises: cf208240cb45
Create Date: 2025-04-03 13:20:40.219319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a7ebe803dc4'
down_revision: Union[str, None] = 'cf208240cb45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trainings', 'image_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trainings', 'image_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
