"""fixing_broken_relationships

Revision ID: cf208240cb45
Revises: 5489dad1af1e
Create Date: 2025-03-31 23:04:14.017890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf208240cb45'
down_revision: Union[str, None] = '5489dad1af1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('training_id', sa.Integer(), nullable=False))
    op.drop_constraint('exercises_trainings_id_fkey', 'exercises', type_='foreignkey')
    op.create_foreign_key(None, 'exercises', 'trainings', ['training_id'], ['id'])
    op.drop_column('exercises', 'trainings_id')
    op.add_column('meals', sa.Column('diet_id', sa.Integer(), nullable=False))
    op.drop_constraint('meals_diets_id_fkey', 'meals', type_='foreignkey')
    op.create_foreign_key(None, 'meals', 'diets', ['diet_id'], ['id'])
    op.drop_column('meals', 'diets_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals', sa.Column('diets_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'meals', type_='foreignkey')
    op.create_foreign_key('meals_diets_id_fkey', 'meals', 'diets', ['diets_id'], ['id'])
    op.drop_column('meals', 'diet_id')
    op.add_column('exercises', sa.Column('trainings_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'exercises', type_='foreignkey')
    op.create_foreign_key('exercises_trainings_id_fkey', 'exercises', 'trainings', ['trainings_id'], ['id'])
    op.drop_column('exercises', 'training_id')
    # ### end Alembic commands ###
