"""Removing the tables meal and exercises from the DB

Revision ID: d7d0a6db548d
Revises: 885ebac1062b
Create Date: 2025-04-17 10:38:18.764598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7d0a6db548d'
down_revision: Union[str, None] = '885ebac1062b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_meals_id', table_name='meals')
    op.drop_table('meals')
    op.drop_index('ix_exercises_id', table_name='exercises')
    op.drop_table('exercises')
    op.alter_column('diets', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('diets', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('exercises',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('bmi_status_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('training_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bmi_status_id'], ['bmi_status.id'], name='exercises_bmi_status_id_fkey'),
    sa.ForeignKeyConstraint(['training_id'], ['trainings.id'], name='exercises_training_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='exercises_pkey')
    )
    op.create_index('ix_exercises_id', 'exercises', ['id'], unique=False)
    op.create_table('meals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('bmi_status_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bmi_status_id'], ['bmi_status.id'], name='meals_bmi_status_id_fkey'),
    sa.ForeignKeyConstraint(['diet_id'], ['diets.id'], name='meals_diet_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='meals_pkey')
    )
    op.create_index('ix_meals_id', 'meals', ['id'], unique=False)
    # ### end Alembic commands ###
