"""Add free_time column to trainings

Revision ID: e8437b967e9d
Revises: 3c9604419fbd
Create Date: 2025-04-02 10:41:08.195715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8437b967e9d'
down_revision: Union[str, None] = '3c9604419fbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainings', sa.Column('free_time', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainings', 'free_time')
    # ### end Alembic commands ###
